### ISSUE TITLE
(in e10s window) Greasemonkey doesn't intercept some userscript links in GitHub (by presenting the installation dialog), though they end with 'user.js'

### ISSUE THREAD

**Issue by darkred** [greasemonkey/greasemonkey#2280]
(using FF Nightly 43.0a1 x64, with GM 3.4.1, in a e10s window)

For example: 
the link that is the `Raw` button in [this page](https://github.com/jerone/UserScripts/blob/63b0f7fd9818c780d05635c9f5acb26afe2d05ef/Github_News_Feed_Filter/Github_News_Feed_Filter.user.js) 

The URL is:
`https://github.com/jerone/UserScripts/raw/63b0f7fd9818c780d05635c9f5acb26afe2d05ef/Github_News_Feed_Filter/Github_News_Feed_Filter.user.js`
_The same link, linkified [here](https://github.com/jerone/UserScripts/raw/63b0f7fd9818c780d05635c9f5acb26afe2d05ef/Github_News_Feed_Filter/Github_News_Feed_Filter.user.js) is intercepted ok._

On the other hand, in a non e10s window (and in FF40 w GM 3.4.1) the link is intercepted ok.

***

For reference, for that same script (in a e10s window), the installation gets intercepted ok 
if you either press the `Install` button in [the script's main page(master branch)](https://github.com/jerone/UserScripts/tree/master/Github_News_Feed_Filter) 
(or if you press the `Github_News_Feed_Filter.user.js` link and then the `Raw` button in that link).

**Comment by janekptacijarabaci** [comment]
See https://github.com/greasemonkey/greasemonkey/blob/3.4.1/modules/installPolicy.js#L82

1)
https://github.com/jerone/UserScripts/blob/master/Github_News_Feed_Filter/Github_News_Feed_Filter.user.js
=>
https://github.com/jerone/UserScripts/raw/master/Github_News_Feed_Filter/Github_News_Feed_Filter.user.js
(https://raw.githubusercontent.com/jerone/UserScripts/master/Github_News_Feed_Filter/Github_News_Feed_Filter.user.js)
__aOriginURI.spec=__
`https://github.com/jerone/UserScripts/blob/master/Github_News_Feed_Filter/Github_News_Feed_Filter.user.js`

2)
https://github.com/jerone/UserScripts/tree/master/Github_News_Feed_Filter
=>
https://github.com/jerone/UserScripts/blob/master/Github_News_Feed_Filter/Github_News_Feed_Filter.user.js
=>
https://github.com/jerone/UserScripts/raw/master/Github_News_Feed_Filter/Github_News_Feed_Filter.user.js
(https://raw.githubusercontent.com/jerone/UserScripts/master/Github_News_Feed_Filter/Github_News_Feed_Filter.user.js)
__aOriginURI.spec=__
`https://github.com/jerone/UserScripts/tree/master/Github_News_Feed_Filter`

**Comment by darkred** [comment]
Thanks for the info

**Comment by janekptacijarabaci** [comment]
I don't think it was necessary to close...

Ad example no. 1):
https://github.com/jerone/UserScripts/raw/master/Github_News_Feed_Filter/Github_News_Feed_Filter.user.js
(https://raw.githubusercontent.com/jerone/UserScripts/master/Github_News_Feed_Filter/Github_News_Feed_Filter.user.js)
__e10s off__: The `Install`  button shows
__e10s on__: The `Install`  button is hidden (it probably is not quite right)

**Comment by darkred** [comment]
Ok, I reopened it,

**Comment by janekptacijarabaci** [comment]
See: https://github.com/greasemonkey/greasemonkey/blob/3.4.1/content/browser.js#L34
e10s on: __The listener will not start.__
e10s off: The listener starts.

**Comment by arantius** [comment]
I've been having trouble understanding/confirming this issue.  I've merged @janekptacijarabaci 's proposed fix and would appreciate feedback on whether 3.5beta3 helps:

https://addons.mozilla.org/firefox/downloads/file/356688/greasemonkey-3.5beta3-fx.xpi?src=devhub

**Comment by arantius** [comment]
In the originally reported case of URL:

https://github.com/jerone/UserScripts/blob/master/Github_News_Feed_Filter/Github_News_Feed_Filter.user.js

The URL already ends in `.user.js` but it's an HTML page describing the source control repository for that file, so we display it rather than intercepting it for script install.  Following the link from there to another URL ending `.user.js` at this point intentionally does not install due to the fix for #1875.

**Comment by arantius** [comment]
Fixing this bug has to include not breaking #1875.  Refreshing myself on the detail of that one.

Trying to edit a `.user.js` file purely via GitHub web UI goes like:

1. GET to https://github.com/USER/REPO/edit/master/FILE.user.js
2. click 'commit changes'
3. POST to https://github.com/USER/REPO/tree-save/master/FILE.user.js

The code committed to fix #1875 implies that we were intercepting the POST in step 3, REJECTing it because it looks like a user script URL, and then that breaks the POST data.  The change was to detect that seemingly unique case and instead ACCEPT the request that was probably a POST (though we don't have any context to know for certain that it is a POST).

**Comment by arantius** [comment]
I've created a test script to reproduce this issue, without using public GitHub: https://gist.github.com/arantius/b57b7c0fc467237d0062

And yes, I've confirmed the situation back from #1875 -- the solution (really, workaround) to that is the cause of this.  The proper fix for this is to fix #1875 without causing this side effect.

**Comment by arantius** [comment]
My best idea so far, but I don't like how big a change it would be, is to switch from `nsIContentPolicy` to `http-on-modify-request`.  The latter should be able to do a `.cancel()` on the request (to switch from loading the script to installing it), but would be a lot of new potentially buggy code to add.

**Comment by arantius** [comment]
I've started working on the approach described immediately above.  A few false starts were frustrating, but now I've made some good/interesting progress.

**Comment by arantius** [comment]
Whoops, the above was e10s disabled.  Enabled, giant mess.  Plus http-on-modify doesn't see local files.

**Comment by arantius** [comment]
Some snippets for my own records:

1

    var runtime = Cc["@mozilla.org/xre/app-info;1"]
        .getService(Ci.nsIXULRuntime);
    dump('Running in parent? '
        + (runtime.processType === Ci.nsIXULRuntime.PROCESS_TYPE_DEFAULT)
        + '\n');

2

    var browser = httpChannel
        .notificationCallbacks.getInterface(Ci.nsILoadContext)
        .topFrameElement;

Which are "useful" but don't actually do what I need in context of the work in progress so far ( https://github.com/arantius/greasemonkey/compare/master...install-observer ) for this issue.

**Comment by arantius** [comment]
The core of the problem I'm facing: http://stackoverflow.com/questions/35344579/

**Comment by arantius** [comment]
Ah!  I've rearranged the problem into something that seems workable.  The `http-on-modify-request` observer is documented ([kinda](https://developer.mozilla.org/en-US/Firefox/Multiprocess_Firefox/Limitations_of_chrome_scripts#HTTP_requests)) to only work in the parent, so it has to live there.  But I don't truly need to send a message to the client, I just need to control whether the request proceeds or not.

And the critical new bit: I can not only .`cancel()`, but also `.suspend()` and `.resume()` the nsIRequest!  So rather than `.sendAsyncMessage()` to get the child to load the page (after we start to download it for an install, and discover that it's an HTML page, not a script), just `.resume()` it and it works like we never did anything.

That and restoring(/keeping) the nsIContentPolicy to see local files (HTTP observer only sees _HTTP_) is looking like it works.  Removes some janky existing code, but needs to be tested, definitely.   Especially the less common features and edge cases around installs.

**Comment by janekptacijarabaci** [comment]
1) Causes an error:
https://github.com/arantius/greasemonkey/compare/master...install-observer#diff-fca536fb25de50f4f011771aa1a74483L7
See:
https://github.com/arantius/greasemonkey/blob/702c6a345e3304e82889d438808839c4fdc7a63c/modules/remoteScript.js#L385

2)
An issue is returned:
https://github.com/greasemonkey/greasemonkey/issues/2292

**Comment by arantius** [comment]
Thanks, that was unintentional, one of the many things I tried and removed, failed to clean up.

0d023e0433cbe65899340be6e31e0cbd5b0aecdb

**Comment by arantius** [comment]
I'm just noticing now that even though `.cancel()` is getting called, the spinner in the tab continues to spin forever.

**Comment by arantius** [comment]
I've just pushed what should be a fix for this, but it's a big change.  I would greatly appreciate any help testing that it works comprehensively; build 3.8beta1 includes this change:

https://addons.mozilla.org/en-US/firefox/addon/greasemonkey/versions/?page=1#version-3.8beta1

**Comment by janekptacijarabaci** [comment]
@arantius 

1) Ad https://github.com/greasemonkey/greasemonkey/commit/fe737c78f61a83273eb2031a143c541b409d02eb#diff-97a81218d24e6e5e19091540aefc4331R10
Twice the same line: Cu.import("resource://gre/modules/Services.jsm");

2) Ad https://github.com/greasemonkey/greasemonkey/issues/2280#issuecomment-183155363:
_An issue is returned:_
_https://github.com/greasemonkey/greasemonkey/issues/2292_
_(update: https://github.com/greasemonkey/greasemonkey/issues/2292#issuecomment-143562376)_
It still holds true...

**Comment by arantius** [comment]
@janekptacijarabaci Please *please* use more words.  I don't know what you mean at all for point 2.

**Comment by janekptacijarabaci** [comment]
Tested on:
GM 3.8beta1+
FF e10s: off

This bug is back ("[e10s off] Two install dialogs"):
https://github.com/greasemonkey/greasemonkey/issues/2292

But perhaps it would be better to report it:

_Last good: 2014-11-17_
_Mozilla/5.0 (Windows NT 6.1; WOW64; rv:36.0) Gecko/20100101 Firefox/36.0_
_Built from https://hg.mozilla.org/mozilla-central/rev/a52bf59965a0_

_First bad: 2014-11-18_
_Mozilla/5.0 (Windows NT 6.1; WOW64; rv:36.0) Gecko/20100101 Firefox/36.0_
_Built from https://hg.mozilla.org/mozilla-central/rev/2a292d225ec0_

_Pushlog
http://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=a52bf59965a0&tochange=2a292d225ec0_

...rather than fix it.

**Comment by arantius** [comment]
> But only version 44.0.2-. The issue has been fixed in newer versions of Firefox (45.0beta1+).

That's probably why I didn't catch it.  And Firefox 45 will be stable soon, so I think I'm comfortable living with this minor usability issue until it is.
