### ISSUE TITLE
Broken in Nightly 56.0a1 (2017-07-26)

### ISSUE THREAD

**Issue by noscript** [greasemonkey/greasemonkey#2533]
Tried both stable 3.11 and dev 3.11beta1. Test script:
```
// ==UserScript==
// @name hello
// @namespace world
// @include *
// ==/UserScript==
alert('Hello world!');
```

**Comment by nazar-pc** [comment]
Same here. Stopped working a few days ago.

**Comment by arantius** [comment]
Works for me.  Going to need more detail.

Should I guess from OP's username that this is actually a conflict with some other extension?

**Comment by nazar-pc** [comment]
I have uBlock Origin installed, but I do not see any blocked requests in network tab in Dev Tools.

Here is what console output looks like on my machine:
```
0 bind() ["jar:file:///home/nazar-pc/.mozilla/firefox/q5eocnir.default/extensions/%7B46551EC9-40F0-4e47-8E18-8E5CF550CFB8%7D.xpi!/components/stylishStyle.js":763]
1 findSql() ["jar:file:///home/nazar-pc/.mozilla/firefox/q5eocnir.default/extensions/%7B46551EC9-40F0-4e47-8E18-8E5CF550CFB8%7D.xpi!/components/stylishStyle.js":810]
2 findEnabled() ["jar:file:///home/nazar-pc/.mozilla/firefox/q5eocnir.default/extensions/%7B46551EC9-40F0-4e47-8E18-8E5CF550CFB8%7D.xpi!/components/stylishStyle.js":82]
3 observe() ["jar:file:///home/nazar-pc/.mozilla/firefox/q5eocnir.default/extensions/%7B46551EC9-40F0-4e47-8E18-8E5CF550CFB8%7D.xpi!/components/stylishStartup.js":21]

0 bind() ["jar:file:///home/nazar-pc/.mozilla/firefox/q5eocnir.default/extensions/%7B46551EC9-40F0-4e47-8E18-8E5CF550CFB8%7D.xpi!/components/stylishStyle.js":760]
1 findSql() ["jar:file:///home/nazar-pc/.mozilla/firefox/q5eocnir.default/extensions/%7B46551EC9-40F0-4e47-8E18-8E5CF550CFB8%7D.xpi!/components/stylishStyle.js":810]
2 find() ["jar:file:///home/nazar-pc/.mozilla/firefox/q5eocnir.default/extensions/%7B46551EC9-40F0-4e47-8E18-8E5CF550CFB8%7D.xpi!/components/stylishStyle.js":72]
3 getAddonByID() ["jar:file:///home/nazar-pc/.mozilla/firefox/q5eocnir.default/extensions/%7B46551EC9-40F0-4e47-8E18-8E5CF550CFB8%7D.xpi!/components/stylishStartup.js":57]
4 callProviderAsync() ["resource://gre/modules/AddonManager.jsm":295]
5 promiseCallProvider/<() ["resource://gre/modules/AddonManager.jsm":319]
6 promiseCallProvider() ["resource://gre/modules/AddonManager.jsm":318]
7 getAddonByID/promises<() ["resource://gre/modules/AddonManager.jsm":2407]
8 from() ["self-hosted":611]
9 getAddonByID() ["resource://gre/modules/AddonManager.jsm":2406]
10 getAddonByID() ["resource://gre/modules/AddonManager.jsm":3577]
11 init() ["jar:file:///home/nazar-pc/.mozilla/firefox/q5eocnir.default/extensions/%7BDD7B8D8D-C0B5-4122-9652-4FCB1E788CD8%7D.xpi!/bootstrap.js":132]
12 onFinalUiStartup() ["jar:file:///home/nazar-pc/.mozilla/firefox/q5eocnir.default/extensions/%7BDD7B8D8D-C0B5-4122-9652-4FCB1E788CD8%7D.xpi!/bootstrap.js":185]

0 bind() ["jar:file:///home/nazar-pc/.mozilla/firefox/q5eocnir.default/extensions/%7B46551EC9-40F0-4e47-8E18-8E5CF550CFB8%7D.xpi!/components/stylishStyle.js":760]
1 findSql() ["jar:file:///home/nazar-pc/.mozilla/firefox/q5eocnir.default/extensions/%7B46551EC9-40F0-4e47-8E18-8E5CF550CFB8%7D.xpi!/components/stylishStyle.js":810]
2 find() ["jar:file:///home/nazar-pc/.mozilla/firefox/q5eocnir.default/extensions/%7B46551EC9-40F0-4e47-8E18-8E5CF550CFB8%7D.xpi!/components/stylishStyle.js":72]
3 getAddonByID() ["jar:file:///home/nazar-pc/.mozilla/firefox/q5eocnir.default/extensions/%7B46551EC9-40F0-4e47-8E18-8E5CF550CFB8%7D.xpi!/components/stylishStartup.js":57]
4 callProviderAsync() ["resource://gre/modules/AddonManager.jsm":295]
5 promiseCallProvider/<() ["resource://gre/modules/AddonManager.jsm":319]
6 promiseCallProvider() ["resource://gre/modules/AddonManager.jsm":318]
7 getAddonByID/promises<() ["resource://gre/modules/AddonManager.jsm":2407]
8 from() ["self-hosted":611]
9 getAddonByID() ["resource://gre/modules/AddonManager.jsm":2406]
10 getAddonByID() ["resource://gre/modules/AddonManager.jsm":3577]
11 <TOP LEVEL> ["chrome://greasemonkey/content/browser.js":13]

0 bind() ["jar:file:///home/nazar-pc/.mozilla/firefox/q5eocnir.default/extensions/%7B46551EC9-40F0-4e47-8E18-8E5CF550CFB8%7D.xpi!/components/stylishStyle.js":760]
1 findSql() ["jar:file:///home/nazar-pc/.mozilla/firefox/q5eocnir.default/extensions/%7B46551EC9-40F0-4e47-8E18-8E5CF550CFB8%7D.xpi!/components/stylishStyle.js":810]
2 find() ["jar:file:///home/nazar-pc/.mozilla/firefox/q5eocnir.default/extensions/%7B46551EC9-40F0-4e47-8E18-8E5CF550CFB8%7D.xpi!/components/stylishStyle.js":72]
3 getAddonByID() ["jar:file:///home/nazar-pc/.mozilla/firefox/q5eocnir.default/extensions/%7B46551EC9-40F0-4e47-8E18-8E5CF550CFB8%7D.xpi!/components/stylishStartup.js":57]
4 callProviderAsync() ["resource://gre/modules/AddonManager.jsm":295]
5 promiseCallProvider/<() ["resource://gre/modules/AddonManager.jsm":319]
6 promiseCallProvider() ["resource://gre/modules/AddonManager.jsm":318]
7 getAddonByID/promises<() ["resource://gre/modules/AddonManager.jsm":2407]
8 from() ["self-hosted":611]
9 getAddonByID() ["resource://gre/modules/AddonManager.jsm":2406]
10 getAddonByID() ["resource://gre/modules/AddonManager.jsm":3577]
11 updateSettings() ["chrome://tabmixplus/content/tab/tab.js":2673]
12 init() ["resource://tabmixplus/TabmixSvc.jsm":180]
13 Tabmix.beforeBrowserInitOnLoad() ["chrome://tabmixplus/content/links/setup.js":49]
14 tabmix_initialization_run() ["chrome://tabmixplus/content/tabmix.js":1235]
15 TMP_EL_onContentLoaded() ["chrome://tabmixplus/content/tabmix.js":322]
16 TMP_EL_handleEvent() ["chrome://tabmixplus/content/tabmix.js":287]

0 bind() ["jar:file:///home/nazar-pc/.mozilla/firefox/q5eocnir.default/extensions/%7B46551EC9-40F0-4e47-8E18-8E5CF550CFB8%7D.xpi!/components/stylishStyle.js":760]
1 findSql() ["jar:file:///home/nazar-pc/.mozilla/firefox/q5eocnir.default/extensions/%7B46551EC9-40F0-4e47-8E18-8E5CF550CFB8%7D.xpi!/components/stylishStyle.js":810]
2 find() ["jar:file:///home/nazar-pc/.mozilla/firefox/q5eocnir.default/extensions/%7B46551EC9-40F0-4e47-8E18-8E5CF550CFB8%7D.xpi!/components/stylishStyle.js":72]
3 getAddonByID() ["jar:file:///home/nazar-pc/.mozilla/firefox/q5eocnir.default/extensions/%7B46551EC9-40F0-4e47-8E18-8E5CF550CFB8%7D.xpi!/components/stylishStartup.js":57]
4 callProviderAsync() ["resource://gre/modules/AddonManager.jsm":295]
5 promiseCallProvider/<() ["resource://gre/modules/AddonManager.jsm":319]
6 promiseCallProvider() ["resource://gre/modules/AddonManager.jsm":318]
7 getAddonByID/promises<() ["resource://gre/modules/AddonManager.jsm":2407]
8 from() ["self-hosted":611]
9 getAddonByID() ["resource://gre/modules/AddonManager.jsm":2406]
10 getAddonByID() ["resource://gre/modules/AddonManager.jsm":3577]
11 checkFirstRun() ["chrome://superstart/content/js/startup.js":452]
12 onLoad() ["chrome://superstart/content/js/startup.js":186]

0 bind() ["jar:file:///home/nazar-pc/.mozilla/firefox/q5eocnir.default/extensions/%7B46551EC9-40F0-4e47-8E18-8E5CF550CFB8%7D.xpi!/components/stylishStyle.js":757]
1 findByMeta() ["jar:file:///home/nazar-pc/.mozilla/firefox/q5eocnir.default/extensions/%7B46551EC9-40F0-4e47-8E18-8E5CF550CFB8%7D.xpi!/components/stylishStyle.js":104]
2 updateStatus() ["chrome://stylish/content/overlay.js":175]
3 urlUpdated() ["chrome://stylish/content/overlay.js":141]
4 init() ["chrome://stylish/content/overlay.js":67]

0 bind() ["jar:file:///home/nazar-pc/.mozilla/firefox/q5eocnir.default/extensions/%7B46551EC9-40F0-4e47-8E18-8E5CF550CFB8%7D.xpi!/components/stylishStyle.js":757]
1 findByMeta() ["jar:file:///home/nazar-pc/.mozilla/firefox/q5eocnir.default/extensions/%7B46551EC9-40F0-4e47-8E18-8E5CF550CFB8%7D.xpi!/components/stylishStyle.js":105]
2 updateStatus() ["chrome://stylish/content/overlay.js":175]
3 urlUpdated() ["chrome://stylish/content/overlay.js":141]
4 init() ["chrome://stylish/content/overlay.js":67]

0 bind() ["jar:file:///home/nazar-pc/.mozilla/firefox/q5eocnir.default/extensions/%7B46551EC9-40F0-4e47-8E18-8E5CF550CFB8%7D.xpi!/components/stylishStyle.js":760]
1 findSql() ["jar:file:///home/nazar-pc/.mozilla/firefox/q5eocnir.default/extensions/%7B46551EC9-40F0-4e47-8E18-8E5CF550CFB8%7D.xpi!/components/stylishStyle.js":810]
2 find() ["jar:file:///home/nazar-pc/.mozilla/firefox/q5eocnir.default/extensions/%7B46551EC9-40F0-4e47-8E18-8E5CF550CFB8%7D.xpi!/components/stylishStyle.js":72]
3 getAddonByID() ["jar:file:///home/nazar-pc/.mozilla/firefox/q5eocnir.default/extensions/%7B46551EC9-40F0-4e47-8E18-8E5CF550CFB8%7D.xpi!/components/stylishStartup.js":57]
4 callProviderAsync() ["resource://gre/modules/AddonManager.jsm":295]
5 promiseCallProvider/<() ["resource://gre/modules/AddonManager.jsm":319]
6 promiseCallProvider() ["resource://gre/modules/AddonManager.jsm":318]
7 getAddonByID/promises<() ["resource://gre/modules/AddonManager.jsm":2407]
8 from() ["self-hosted":611]
9 getAddonByID() ["resource://gre/modules/AddonManager.jsm":2406]
10 getAddonByID() ["resource://gre/modules/AddonManager.jsm":3577]
11 enable/<() ["resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/preferences/native-options.js":34]
12 enable() ["resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/preferences/native-options.js":28]
13 run() ["resource://gre/modules/commonjs/sdk/addon/runner.js":108]
14 startup/</<() ["resource://gre/modules/commonjs/sdk/addon/runner.js":83]
15 process() ["resource://gre/modules/Promise-backend.js":922]
16 walkerLoop() ["resource://gre/modules/Promise-backend.js":806]
17 bound walkerLoop() ["self-hosted":945]
18 bound walkerLoop() ["self-hosted":945]
19 scheduleWalkerLoop/<() ["resource://gre/modules/Promise-backend.js":742]
20 getExtensionInfo() ["jar:file:///home/nazar-pc/.mozilla/firefox/q5eocnir.default/extensions/%7BDD7B8D8D-C0B5-4122-9652-4FCB1E788CD8%7D.xpi!/bootstrap.js":21]
21 init/<() ["jar:file:///home/nazar-pc/.mozilla/firefox/0 bind() ["jar:file:///home/nazar-pc/.mozilla/firefox/q5eocnir.default/extensions/%7B46551EC9-40F0-4e47-8E18-8E5CF550CFB8%7D.xpi!/components/stylishStyle.js":760]
1 findSql() ["jar:file:///home/nazar-pc/.mozilla/firefox/q5eocnir.default/extensions/%7B46551EC9-40F0-4e47-8E18-8E5CF550CFB8%7D.xpi!/components/stylishStyle.js":810]
2 find() ["jar:file:///home/nazar-pc/.mozilla/firefox/q5eocnir.default/extensions/%7B46551EC9-40F0-4e47-8E18-8E5CF550CFB8%7D.xpi!/components/stylishStyle.js":72]
3 getAddonByID() ["jar:file:///home/nazar-pc/.mozilla/firefox/q5eocnir.default/extensions/%7B46551EC9-40F0-4e47-8E18-8E5CF550CFB8%7D.xpi!/components/stylishStartup.js":57]
4 callProviderAsync() ["resource://gre/modules/AddonManager.jsm":295]
5 promiseCallProvider/<() ["resource://gre/modules/AddonManager.jsm":319]
6 promiseCallProvider() ["resource://gre/modules/AddonManager.jsm":318]
7 getAddonByID/promises<() ["resource://gre/modules/AddonManager.jsm":2407]
8 from() ["self-hosted":611]
9 getAddonByID() ["resource://gre/modules/AddonManager.jsm":2406]
10 getAddonByID() ["resource://gre/modules/AddonManager.jsm":3577]
11 enable/<() ["resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/preferences/native-options.js":34]
12 enable() ["resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/preferences/native-options.js":28]
13 run() ["resource://gre/modules/commonjs/sdk/addon/runner.js":108]
14 startup/</<() ["resource://gre/modules/commonjs/sdk/addon/runner.js":83]
15 process() ["resource://gre/modules/Promise-backend.js":922]
16 walkerLoop() ["resource://gre/modules/Promise-backend.js":806]
17 bound walkerLoop() ["self-hosted":945]
18 bound walkerLoop() ["self-hosted":945]
19 scheduleWalkerLoop/<() ["resource://gre/modules/Promise-backend.js":742]
20 getExtensionInfo() ["jar:file:///home/nazar-pc/.mozilla/firefox/q5eocnir.default/extensions/%7BDD7B8D8D-C0B5-4122-9652-4FCB1E788CD8%7D.xpi!/bootstrap.js":21]
21 init/<() ["jar:file:///home/nazar-pc/.mozilla/firefox/0 bind() ["jar:file:///home/nazar-pc/.mozilla/firefox/q5eocnir.default/extensions/%7B46551EC9-40F0-4e47-8E18-8E5CF550CFB8%7D.xpi!/components/stylishStyle.js":760]
1 findSql() ["jar:file:///home/nazar-pc/.mozilla/firefox/q5eocnir.default/extensions/%7B46551EC9-40F0-4e47-8E18-8E5CF550CFB8%7D.xpi!/components/stylishStyle.js":810]
2 find() ["jar:file:///home/nazar-pc/.mozilla/firefox/q5eocnir.default/extensions/%7B46551EC9-40F0-4e47-8E18-8E5CF550CFB8%7D.xpi!/components/stylishStyle.js":72]
3 getAddonByID() ["jar:file:///home/nazar-pc/.mozilla/firefox/q5eocnir.default/extensions/%7B46551EC9-40F0-4e47-8E18-8E5CF550CFB8%7D.xpi!/components/stylishStartup.js":57]
4 callProviderAsync() ["resource://gre/modules/AddonManager.jsm":295]
5 promiseCallProvider/<() ["resource://gre/modules/AddonManager.jsm":319]
6 promiseCallProvider() ["resource://gre/modules/AddonManager.jsm":318]
7 getAddonByID/promises<() ["resource://gre/modules/AddonManager.jsm":2407]
8 from() ["self-hosted":611]
9 getAddonByID() ["resource://gre/modules/AddonManager.jsm":2406]
10 getAddonByID() ["resource://gre/modules/AddonManager.jsm":3577]
11 enable/<() ["resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/preferences/native-options.js":34]
12 enable() ["resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/preferences/native-options.js":28]
13 run() ["resource://gre/modules/commonjs/sdk/addon/runner.js":108]
14 startup/</<() ["resource://gre/modules/commonjs/sdk/addon/runner.js":83]
15 process() ["resource://gre/modules/Promise-backend.js":922]
16 walkerLoop() ["resource://gre/modules/Promise-backend.js":806]
17 bound walkerLoop() ["self-hosted":945]
18 bound walkerLoop() ["self-hosted":945]
19 scheduleWalkerLoop/<() ["resource://gre/modules/Promise-backend.js":742]
20 getExtensionInfo() ["jar:file:///home/nazar-pc/.mozilla/firefox/q5eocnir.default/extensions/%7BDD7B8D8D-C0B5-4122-9652-4FCB1E788CD8%7D.xpi!/bootstrap.js":21]
21 init/<() ["jar:file:///home/nazar-pc/.mozilla/firefox/0 bind() ["jar:file:///home/nazar-pc/.mozilla/firefox/q5eocnir.default/extensions/%7B46551EC9-40F0-4e47-8E18-8E5CF550CFB8%7D.xpi!/components/stylishStyle.js":760]
1 findSql() ["jar:file:///home/nazar-pc/.mozilla/firefox/q5eocnir.default/extensions/%7B46551EC9-40F0-4e47-8E18-8E5CF550CFB8%7D.xpi!/components/stylishStyle.js":810]
2 find() ["jar:file:///home/nazar-pc/.mozilla/firefox/q5eocnir.default/extensions/%7B46551EC9-40F0-4e47-8E18-8E5CF550CFB8%7D.xpi!/components/stylishStyle.js":72]
3 getAddonByID() ["jar:file:///home/nazar-pc/.mozilla/firefox/q5eocnir.default/extensions/%7B46551EC9-40F0-4e47-8E18-8E5CF550CFB8%7D.xpi!/components/stylishStartup.js":57]
4 callProviderAsync() ["resource://gre/modules/AddonManager.jsm":295]
5 promiseCallProvider/<() ["resource://gre/modules/AddonManager.jsm":319]
6 promiseCallProvider() ["resource://gre/modules/AddonManager.jsm":318]
7 getAddonByID/promises<() ["resource://gre/modules/AddonManager.jsm":2407]
8 from() ["self-hosted":611]
9 getAddonByID() ["resource://gre/modules/AddonManager.jsm":2406]
10 getAddonByID() ["resource://gre/modules/AddonManager.jsm":3577]
11 enable/<() ["resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/preferences/native-options.js":34]
12 enable() ["resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/preferences/native-options.js":28]
13 run() ["resource://gre/modules/commonjs/sdk/addon/runner.js":108]
14 startup/</<() ["resource://gre/modules/commonjs/sdk/addon/runner.js":83]
15 process() ["resource://gre/modules/Promise-backend.js":922]
16 walkerLoop() ["resource://gre/modules/Promise-backend.js":806]
17 bound walkerLoop() ["self-hosted":945]
18 bound walkerLoop() ["self-hosted":945]
19 scheduleWalkerLoop/<() ["resource://gre/modules/Promise-backend.js":742]
20 getExtensionInfo() ["jar:file:///home/nazar-pc/.mozilla/firefox/q5eocnir.default/extensions/%7BDD7B8D8D-C0B5-4122-9652-4FCB1E788CD8%7D.xpi!/bootstrap.js":21]
21 init/<() ["jar:file:///home/nazar-pc/.mozilla/firefox/0 bind() ["jar:file:///home/nazar-pc/.mozilla/firefox/q5eocnir.default/extensions/%7B46551EC9-40F0-4e47-8E18-8E5CF550CFB8%7D.xpi!/components/stylishStyle.js":760]
1 findSql() ["jar:file:///home/nazar-pc/.mozilla/firefox/q5eocnir.default/extensions/%7B46551EC9-40F0-4e47-8E18-8E5CF550CFB8%7D.xpi!/components/stylishStyle.js":810]
2 find() ["jar:file:///home/nazar-pc/.mozilla/firefox/q5eocnir.default/extensions/%7B46551EC9-40F0-4e47-8E18-8E5CF550CFB8%7D.xpi!/components/stylishStyle.js":72]
3 getAddonByID() ["jar:file:///home/nazar-pc/.mozilla/firefox/q5eocnir.default/extensions/%7B46551EC9-40F0-4e47-8E18-8E5CF550CFB8%7D.xpi!/components/stylishStartup.js":57]
4 callProviderAsync() ["resource://gre/modules/AddonManager.jsm":295]
5 promiseCallProvider/<() ["resource://gre/modules/AddonManager.jsm":319]
6 promiseCallProvider() ["resource://gre/modules/AddonManager.jsm":318]
7 getAddonByID/promises<() ["resource://gre/modules/AddonManager.jsm":2407]
8 from() ["self-hosted":611]
9 getAddonByID() ["resource://gre/modules/AddonManager.jsm":2406]
10 getAddonByID() ["resource://gre/modules/AddonManager.jsm":3577]
11 enable/<() ["resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/preferences/native-options.js":34]
12 enable() ["resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/preferences/native-options.js":28]
13 run() ["resource://gre/modules/commonjs/sdk/addon/runner.js":108]
14 startup/</<() ["resource://gre/modules/commonjs/sdk/addon/runner.js":83]
15 process() ["resource://gre/modules/Promise-backend.js":922]
16 walkerLoop() ["resource://gre/modules/Promise-backend.js":806]
17 bound walkerLoop() ["self-hosted":945]
18 bound walkerLoop() ["self-hosted":945]
19 scheduleWalkerLoop/<() ["resource://gre/modules/Promise-backend.js":742]
20 getExtensionInfo() ["jar:file:///home/nazar-pc/.mozilla/firefox/q5eocnir.default/extensions/%7BDD7B8D8D-C0B5-4122-9652-4FCB1E788CD8%7D.xpi!/bootstrap.js":21]
21 init/<() ["jar:file:///home/nazar-pc/.mozilla/firefox/
```

**Comment by noscript** [comment]
@arantius No other extensions were installed, using a freshly created profile. I tried to switch between FF Stable and Nightly using the same profile, alert does not appear in Nightly.

Running on Debian 8 x64.

**Comment by janekptacijarabaci** [comment]
On Linux confirmed:

__Last good: Firefox 56.0a1 (2017-07-25)__
Built from https://hg.mozilla.org/mozilla-central/rev/131e19a573e901fb4d01b471b11b7916420b9fee

__First bad: Firefox 56.0a1 (2017-07-26)__
Built from https://hg.mozilla.org/mozilla-central/rev/e8400551c2e39f24c75a009ebed496c7acd7bf47

Pushlog
https://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=131e19a573e901fb4d01b471b11b7916420b9fee&tochange=e8400551c2e39f24c75a009ebed496c7acd7bf47

Throws an error in Browser Console:
```
TypeError: el is null
emptyEl.js:4:10
```

See also this message: "greasemonkey:menu-command-response".

Temporary fix:
`about:config`
`security.sandbox.content.level` = `1`

**Comment by janekptacijarabaci** [comment]
See also: https://bugzilla.mozilla.org/show_bug.cgi?id=1385712

**Comment by AlexandreBonneau** [comment]
For info, this is broken on `56.0b1` too.

**Comment by gcp** [comment]
You need 56b02 for that setting to work correctly. 56b03 will have that fix and the level 2 setting which should fix this, by default.

**Comment by faelsoto** [comment]
I'm on 56.0b2 and it's not working for me, altough what happens it's that Greasemonkey says that there are no scripts installed to run on this page. Can't tell if it's related to this issue or not.

**Comment by dequis** [comment]
@faelsoto did you change `security.sandbox.content.level` from 3 to 2? (or 1)

Or just wait for 56.0b3, releasing tomorrow-ish.

**Comment by AlexandreBonneau** [comment]
on `56.0b2`, I just tested modifying `security.sandbox.content.level` to `2`, then to `1`, tried to refresh a page on which I have a custom greasemonkey script, tried to open a new tab and go to that same page ; this does not fix anything unfortunately.

**Comment by gcp** [comment]
Make sure to restart the browser after changing that setting.

**Comment by AlexandreBonneau** [comment]
Ok, setting `security.sandbox.content.level` to `2`, *then* restarting fix the problem. Congrats.

Side note: What are the implications of changing that security level exactly?

**Comment by gcp** [comment]
>Side note: What are the implications of changing that security level exactly?

https://wiki.mozilla.org/Security/Sandbox#Content_Levels_2

In simple terms, with level 2 an attacker that finds one security hole in Firefox won't be able to take over the browser or PC, but can still access sensitive data such as your passwords, cookies, etc. Level 3 closes that hole.

There were too many outstanding compatibility issues to leave 3 enabled on 56, though we plan to enable it in 57, which has a load more fixes. Note that this is specific to Linux, macOS and Windows already shipped a stricter sandbox.

**Comment by dequis** [comment]
>Bankruptcy milestone

Wow that sounds sad. But isn't this pretty much fixed? Firefox 57.0a1 has level 3, but I'm pretty sure I saw other fixes for this same bug, and I just tested nightly buildid 20170816100153 and it works.

**Comment by gcp** [comment]
Nightly was fixed by bug 1385891. There's nothing Greasemonkey needs to do to fix this on their side.

(Aside from the obvious WebExtensions elephant in the room, and the controversy over whether they should have filesystem access or not, but that's being dealt with in other issues)
