### ISSUE TITLE
Editor forgets the content I paste into the "New user script template"

### ISSUE THREAD

**Issue by StigNygaard** [greasemonkey/greasemonkey#2721]
As mentioned in forum the other day, I have no luck creating a user script via "New user script..." when pasting script-code into the editor. I have now tried some other scripts too, but content revert back to the initial 5-lines template content when re-starting the browser.

To reproduce in GM4.1Beta4 on FF58Beta4DevEdition:
1) Create a new script using the "New User script..." menu item in monkey menu.
2) Copy full page content from for example https://raw.githubusercontent.com/murdos/musicbrainz-userscripts/master/discogs_importer.user.js , or mark the script-code and copy from for example https://greasyfork.org/en/scripts/21153-stig-s-last-fm-album-linkr/code.
3) Paste into monkey-editor (To replace, mark the 5 initial lines before pasting). Note the tab gets a star to mark unsaved content.
4) Press Ctrl-S to save. Star is gone (but script name in tab still says something like "Unnamed Script nnnnnn").
5) Close monkey-editor window.
6) Reopen script in monkey-editor from Monkey menu. It's still there.
7) Close and reopen browser.
8) Reopen script in monkey-editor from Monkey menu. Now, it's back to the initial 5 lines template!?!

Next I tried copying the 5-lines template out into an external text-editor, change the @name of the script and paste it back into the open monkey-editor. This time it updates script name in the tab, plus it remembers after restarting browser. I have no clue to what's going on?...

**Comment by S-ed** [comment]
I've tested it, and seems:
@require and @icon preventing script from being saved (name of the script will change on the list and the tab, Ctrl+S and F5).

**Comment by Sxderp** [comment]
> Press Ctrl-S to save. Star is gone (but script name in tab still says something like "Unnamed Script nnnnnn").

At the moment this is not directly related to your issue. I don't believe the script name on the tab is ever updated on save. It's on the todo list.

**Comment by Sxderp** [comment]
Oh, I think this was the issue I found early and is solved with #2707. Unfortunately that hasn't been included in any releases yet.

**Comment by arantius** [comment]
I just tried:

1. Click 'new script' and do nothing, close the editor.
1. Close and restart Firefox.  Same script is still there.
1. Edit said script, to only append a `console.log(1)` line.
1. Open a page, see a "1" in the console.
1. Restart Firefox, load pages: I still see console entries.
1. Open this script in the editor, the source is still there.
1. Edit the script further to change the `@name` and to log "2"
1. Load a page, I see "2" in my console.
1. Restart Firefox, load a page.  Still see "2" in my console.
1. Open the editor, still see my changes.
1. Edit the script to add a new `@require` line (it doesn't start with any) and change the log to "3".
1. Load a page, it logs "2" still.
1. Reopen the previously closed editor, source is still there.  Whitespace change and save again.
1. Load a page, it logs "2" still.
1. Restart Firefox, load a page.  Still see "2" in my console.

So it's really the `@require` that does it, something is not handled correctly there.

Oh and step N: notice a comment above that says basically this.

**Comment by arantius** [comment]
And now I see the pre-require source in the editor so *maybe* I was mistaken at one step above.

This was in 4.1beta4, so sync in other changes and repeat.  At step 11 above, the tab for the new require appears when I hit save.  And the new log value shows.

So considering this a dupe of #2706

**Comment by arantius** [comment]
And now I see the pre-require source in the editor so *maybe* I was mistaken at one step above.

This was in 4.1beta4, so sync in other changes and repeat.  At step 11 above, the tab for the new require appears when I hit save.  And the new log value shows.

So considering this a dupe of #2706

**Comment by StigNygaard** [comment]
Okay, not that I understood much of above. But I think the conclusion was that it probably was solved already, so I should wait for beta 5 and see.
I have noticed another weird thing regarding editor and tabs. But there have been a lot of checkins since beta4, so maybe it makes sense to wait for beta5 and see how it works out? Will we see beta5 any time soon?

**Comment by Sxderp** [comment]
> Will we see beta5 any time soon?

A new release usually hits about once a week.

**Comment by arantius** [comment]
But this is the week of Thanksgiving and I'm traveling, so things are hard to predict ...
